### ISSUE TITLE
Skill Modifiers API

### ISSUE THREAD

**Issue by stocky37** [EpicSevenDB/gamedatabase#114]
I noticed you mentioned in the patch notes that you would be looking at adding unit skill modifiers soon. Has there been any work on this as of yet, or any thought put into the API design?

According to [Datamined Skill Data & Damage Calculations](https://www.reddit.com/r/EpicSeven/comments/abfdo2/datamined_skill_data_and_damage_calculations/), the following values are used for each skill:

- Atk modifier
- Power modifier
- Other stat modifiers (spd, missing hp, max hp etc.)

How do you think this should fit into the current API?

**Comment by RaphaelDDL** [comment]
Yeah, so MaxNumbers gave me a json with the multipliers. E.g.

![image](https://user-images.githubusercontent.com/1087109/52488775-be139d00-2ba7-11e9-8616-6ab58a32de0b.png)
![image](https://user-images.githubusercontent.com/1087109/52488836-e26f7980-2ba7-11e9-866a-a819e398a9a7.png)

Considering they are skill-specific, I was thinking in adding them to the skill objects of each hero.
I still just don't know how to translate this easily.

I'll normally need att_rate and secondary, but some have different things, like soulburn increases the att_rate, and so on.

Suggestions?

**Comment by kmalone86** [comment]
Adding to the skill makes sense, but the variable formats depends on how we will use them.

Made this python script to copy from MaxNumber's json to our json for a hero. Can use it after we decide if we want to change the values like  "20%" to 0.2

<pre><code>
#!/usr/bin/python

import sys
import json
from collections import OrderedDict
import os.path

if len(sys.argv) < 3:
  print('Requires 2 arguments, modiferFileName & HeroFileName.')
  quit()

inputFile = sys.argv[1]
outputFile = sys.argv[2]
if os.path.isfile(inputFile) == False:
   print(inputFile+' is not a file.')
   quit()
if os.path.isfile(outputFile) == False:
   print(outputFile+' is not a file.')
   quit()

data = {}
with open(outputFile, 'r') as outfile: 
    out = json.load(outfile, object_pairs_hook=OrderedDict)
    #print(json.dumps(out, indent=4))
    print('Character: ' + out['name'])
    with open(inputFile) as json_file:  
        data = json.load(json_file)
        modHero = 0
        for p in data:
            if p['character'] == out['name']:
                print('Found character: ' + out['name'])
                modHero = p
                break
        if modHero == 0:
            print(outputFile + '\'s modifier data was not found.')
            quit()
        # Now that we have found Hero in both files, write data.
        skillOutList = out['skills']
        i = 0
        for skillOut in skillOutList:
            print('Adding to skill '+ skillOut['name'])
            i = i + 1;
            skillName = 'skill_'+str(i)
            if skillName not in modHero:
                break
            skillIn = modHero[skillName]
            if 'modifiers' not in modHero:
                skillOut['modifiers'] = OrderedDict()
            skillInMod = skillOut['modifiers']
            skillInMod['attRate'] = skillIn['att_rate']
            skillInMod['soulBurnAttRate'] = skillIn['soul_burn_att_rate']
            skillInMod['bonusDmg1Atk'] = skillIn['Bonus_Dmg1_atk%']
            skillInMod['bonusDmg1Conditions'] = skillIn['Bonus_Dmg1_Conditions']
            skillInMod['bonusDmg2'] = skillIn['Bonus_Dmg2']
            skillInMod['bonusDmg2Conditions'] = skillIn['Bonus_Dmg2_Conditions']
            skillInMod['secondaryScaling'] = skillIn['secondary_scaling']
            skillInMod['secondaryStat'] = skillIn['secondary_stat']
            skillInMod['secondaryStatBurn'] = skillIn['secondary_stat_burn']
            skillInMod['beneficialEffect'] = skillIn['Beneficial_Effect']
            skillInMod['soulburnBeneficialEffect'] = skillIn['Soulburn_Beneficial_Effect']
            skillInMod['soulburnSecondaryStat'] = skillIn['Soulburn_Secondary_Stat']
            skillInMod['mult'] = skillIn['MULT']
            skillInMod['targets'] = skillIn['targets']
        #print(json.dumps(out, indent=4))
with open(outputFile, 'w') as outfile: 
    json.dump(out, outfile, indent=4, separators=(',', ': '))
    outfile.write("\n")

</code></pre>

**Comment by stocky37** [comment]
Hey, sorry I've been away so haven't had a chance to look at this just yet. I'm going to have a bit of a deeper think about it since my end goal is to be able to programmatically calculate skill damage and effects. I think that in order to facilitate my goal, the existing skills api will likely have to change as well.

If that's the case, while I figure out how that should look, I'm not particularly fussed in what the api for this looks like in the meantime.

**Comment by kmalone86** [comment]
I have been slowly trying to wrap my head around how to add the data to the database, while still being readable. I am a bit sick at the moment, so taking a break for few days.

Since there are just so many unique variables, it is hard to just have variables. I am leaning more to just storing the formula like the following.
<pre><code>
            ],
            "modifiers": {
                "formulas": [
                    {
                        "damage": "((1.0 * atk) + (1.0 * def) + (1.0 * hp)) * (1 + (0.0 * spd)) * standardDamageFormula"
                    }
                ],
                "pow": 1.0,
                "condition": [
                    {
                        "description": "Soul Burn",
                        "formulas": [
                            {
                                "damage": "((1 * atk) + (1 * def) + (1 * hp)) * (1 + (0.0 * spd)) * standardDamageFormula"
                            }
                        ]
                    }
                ]
            }
</code></pre>

Still working on if some cases are just too weird. Like Zeno's S2 passive. Where his S2 increases his S3 damage, so a variable from S2 needs to be carried over to S3.
<pre><code>

            "modifiers": {
                "formulas": [
                  {
		    "def": "(0.05 * triggers)",
                  },
                  {
		    "passiveSkillModifer": "1+(0.05 * triggers)",
                  },
		],
                "pow": 1,
                "condition": [
                    {
                        "description": "Max molagora",
                       "formulas": [
                        {
		            "def": "(0.08 * triggers)",
                        },
                        {
		          "passiveSkillModifer": "1+(0.08 * triggers)",
                        },
		       ]
                    }
                ]
            }
</code></pre>

**Comment by stocky37** [comment]
From everything I've seen, there is only a single damage formula. Heroes jsut seem to have different modifieres and scalings that affect it. Should we only be storing all of these modifiers instead? I'm not sure I see any value in storing these "formulas".

**Comment by stocky37** [comment]
Here's a list of different types of damage scalings I can think of off the top of my head:

- Attack
- Defense
- Speed
- Damage (from skillups, C. Dom stacks, etc.)
- Max HP
- Current HP
- Enemy Max HP
- Enemy Current HP?

Have I left any out?

**Comment by stocky37** [comment]
Either of the following could probably handle at least the majority of use cases:
```json
{
  "damageModifiers": {
    "pow": 1,
    "atk": 1.1,
    "enemyHP": 0.04
  }
}
```

```json
{
  "damageModifiers": [
    {
      "type": "atk",
      "value": 1.1
    },
    {
      "type": "enemyHP",
      "value": 0.04
    },
    {
      "type": "pow",
      "value": 1
    }
  ]
}
```

**Comment by kmalone86** [comment]
Right now, most cases follow the formula, I was just worried they change it in special cases.

Some special cases I recall off top of head. Krau has a +100% hp lost (maxHp-curHp) as damage.
Baal & Sezan have a 10% per debuff on enemy so (1 + numDebuffs*0.1)

**Comment by stocky37** [comment]
Oh yeah, I'd forgotten about B&S. I'll add it to my list up there.

What I was thinking with these custom ones, is that you could include them in the generic formula but then set the modifiers to 0 (or absent) for heroes that don't scale in that way. So if the generic formula is (and it's not, but just for point of argument) `atk * (1+debuffs*debuffModifier)`, if `debuffModifier` is 0 then it just cancels out of the formula. Can you think of cases where that wouldn't work?

**Comment by kmalone86** [comment]
As far as your examples, 1 would be easier, but I am unsure how Raphael's code will read it in. It may require every possible value to be set, so if you 30 values with only 2 set, just looks messy.

Reading the descriptions it sounds like it is a modifier in it own. A pure damage increase.

Even with the debuffs, B&S need the 1+(numDebuff*.1), but then Zerato needs a flat 0.3% if any debuffs, So we would need a numDebuffMulti: 0.1  and debuffMulti:0.3

**Comment by stocky37** [comment]
Woops o.O

**Comment by stocky37** [comment]
> Zerato needs a flat 0.3% if any debuffs

Interesting, that would definitely have to be a separate modifier then. I'm going to make another comment with a table containing all the different types of modifiers we can see so we can use it for reference.

**Comment by kmalone86** [comment]
Corvus was always the one I looked at as it was so weird.
Atk modifer is 0.7 + def modifier of 0.9
But after using his S3, for 3 turns, these values change.
Atk: 0.9 def:1.2

**Comment by stocky37** [comment]
| Modifier | Example Heroes | Notes |
| ----------- | ---------------------- | -------- |
| Pow | All | |
| Attack | All | |
| Defense | Rose S1 | |
| Speed | Cidd, Vildred | |
| Health | Assassin Cartuja | |
| Health missing | Kayron | |
| # of targets | Bellona S2 |
| Single target bonus | Yuna | |
| Enemy debuffed | Zerato | |
| Enemy buffed | Yufine | |
| # of enemy debuffs | Baal & Sezan | |
| Corvus | o.O | |

**Comment by stocky37** [comment]
If soulburns are just increasing modifiers, you could just represent them as either the total new modifier for the modifier it's changing, or the additional modifier percentage that it is adding. For example, for a simple one like Shadow Rose S3:
```json
{
  "damageModifiers": {
    "atk": 0.7
  },
  "soulBurn": {
    "atk": 0.9
  }
}
```
**or**
```json
{
  "damageModifiers": {
    "atk": 0.7
  },
  "soulBurn": {
    "atk": 0.2
  }
}
```

This should be do-able for most/all of the modifiers I've listed so far. Although there are other effects that soulburn can have, such as ignores resistance etc. so we'd need to fit that in somehow as well.

**Comment by stocky37** [comment]
Option 2 that I specified previously is starting to look more appealling in the case here we want to specify more than just the scaling percentage for that type. For instance, we could then combine `hp` and `targetHp` into one block:
```json
{
  "type": "hp",
  "value": 0.2,
  "target": "self|enemy"
}
```

Or in the case of `singleTargetBonus`:
```json
{
  "type": "singleTargetBonus",
  "values": {
    "single": 1.4,
    "multi": 1.2
  }
}
```

**Comment by kmalone86** [comment]
Tamarinne's skills are separate S1, S2, S3, S4(S1-2), S5(S2-2), so different modifiers can be put in each.

For option 2, it may be useful to have "additive|multiplicative" to help know how it is used.

For the singleTargetBonus,  I assume we would need twoTargetBonus or ThreeTargetBonus if in future exact values matter.

I have yet to see a soul burn that has a special case, so in your example of 0.7 going to 0.9 on soulburn. It is hard to tell if there is a special case in future that makes 0.7 to go to 0.8 then soulburn further it, we just can't tell if the soulburn adds to 1.0 or soulburn+special case is something completely different. Due to this, I would say to just list the full value.

I had experimented with this kind of things before. I had "conditions" like I had above, but the modifier values within the condition would overwrite the base values.

cdom & karin will need a critModifier, which crit would be another condition like soul burn.

Passives are the weird one (cdom & zeno)

**Comment by stocky37** [comment]
> For option 2, it may be useful to have "additive|multiplicative" to help know how it is used.

Do you mean to represent the following: `(atk * atk_rate + additive modifiers) * multiplicative modifiers` ?

> For the singleTargetBonus, I assume we would need twoTargetBonus or ThreeTargetBonus if in future exact values matter.

The way it's designed leans me towards thinking that this won't happen, since then they would be more likely to just use the `numTargets` scaling. We will probably be safe if we ignore it for now.

Otherwise we could just make it even more generic with something like the following:

```json
{
  "type": "numTargetBreakpoints",
  "base": 1.2,
  "breakpoints": [{
    "numTargets": 1,
    "modifier": 1.4
  },
}
```

> cdom & karin will need a critModifier, which crit would be another condition like soul burn.

I'll add it to the table

> Passives are the weird one (cdom & zeno)

Definitely. We could just ignore them for an initial implementation and think about it later?

**Comment by kmalone86** [comment]
As for additive|multiplicative, I mainly mean that some stats are added before multiplied. For example att_rate would be part of the additive. It is att_rate*atk +.....  (for corvus would be  + def_rate*def). This would be different than cases of speed which are multiplicative (1 + (spd_rate*spd)) *(remaining actions).

As for targets, I am trying to make sure we don't put ourselves in a corner. Right now, the targets may just be multiplicative modifiers, but who knows if the target will affect att_rate at some point similar to * Charlotte's based on focus.

For our own sanity it may be worth skipping passives for now, yes.

**Comment by stocky37** [comment]
> As for additive|multiplicative, I mainly mean that some stats are added before multiplied.

Ok cool, that's how I understood it as well. In that case, yeah that would actually be pretty helpful :)

> As for targets, I am trying to make sure we don't put ourselves in a corner. Right now, the targets may just be multiplicative modifiers, but who knows if the target will affect att_rate at some point similar to * Charlotte's based on focus.

I can't see us painting ourselves into a corner if we head in this direction. Any modifiers similar to Charlotte's could just be a new type of modifier and it should be fine to add new ones as they come up.

**Comment by stocky37** [comment]
As for Charlotte, a modifier like the following could work:

```json
{
  "type": "atkRateFocus",
  "values": [
    0.8,
    0.8,
    1,
    1.3,
    1.7,
    2.4
  ]
}
```

It would have to be handled separately from the other types of modifiers however.

**Comment by stocky37** [comment]
Actually, if we use your additive/multiplicative idea, we could make some of these even more generic. I'm thinking maybe somtehing along the lines of `statModifier` & `statModifierPerFocus` (for Charlotte's case) so we'd end up with:

```json
{
  "name": "statModifier",
  "stat": "atk|def|hp|spd|critDmg",
  "type": "additive|multiplicative",
  "modifier": 1.2
}
```

and
```json
{
  "name": "statModifierPerFocus",
  "stat": "atk|def|hp|spd|critDmg",
  "type": "additive|multiplicative",
  "modifiers": [
    0.8,
    0.8,
    1,
    1.3,
    1.7,
    2.4
  ]
}
```

Can you see any issues with combining most of the generic stat modifiers with the above?

**Comment by stocky37** [comment]
<table>
  <thead>
  <tr>
    <th>Modifier</th>
    <th>Examples</th>
    <th>Proposed JSON</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Pow</td>
    <td>All Heroes</td>
    <td>
      <pre lang="json">{
  "name": "pow",
  "value": 1.1
}</pre>
    </td>
  </tr>
  <tr>
    <td>Attack</td>
    <td>All Heroes</td>
    <td>
      <pre lang="json">{
  "name": "statModifier",
  "stat": "atk",
  "type": "additive",
  "value": 1.1
}</pre>
    </td>
  </tr>
  <tr>
    <td>Health</td>
    <td>Krau (S1,S2)</td>
    <td>
      <pre lang="json">{
  "name": "statModifier",
  "stat": "hp",
  "type": "additive",
  "value": 0.13
}</pre>
    </td>
  </tr>
  <tr>
    <td>Defense</td>
    <td>Pyllis (S1,S3)</td>
    <td>
      <pre lang="json">{
  "name": "statModifier",
  "stat": "def",
  "type": "additive",
  "value": 0.7
}</pre>
    </td>
  </tr>
  <tr>
    <td>Speed</td>
    <td>Wanderer Silk</td>
    <td>
      <pre lang="json">{
  "name": "statModifier",
  "stat": "spd",
  "type": "multiplicative",
  "value": 0.001125
}</pre>
    </td>
  </tr>
  <tr>
    <td>Crit Damage</td>
    <td>Challenger Dominiel (S1)</td>
    <td>
      <pre lang="json">{
  "name": "statModifier",
  "stat": "crd",
  "type": "multiplicative",
  "value": 1.2
}</pre>
    </td>
  </tr>
  <tr>
    <td>Health Missing (%)</td>
    <td>Kayron (S1,S3)</td>
    <td>
      <pre lang="json">{
  "name": "hpMissing",
  "type": "multiplicative",
  "target": "self",
  "value": 1.003,
  "breakpoint": 0.1
}</pre>
    </td>
  </tr>
  <tr>
    <td>Health Missing (static)</td>
    <td>Krau (S3)</td>
    <td>
      <pre lang="json">{
  "name": "hpMissingStatic",
  "type": "additive",
  "value": 0.53571,
  "breakpoint": 1
}</pre>
    </td>
  </tr>
  <tr>
    <td>Target max health</td>
    <td>Bellona (S1)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Target Health Missing</td>
    <td>Sez (S1,S3)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Per Target</td>
    <td>Bellona (S2)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Single Target Bonus</td>
    <td>Yuna (S1,S3)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Target Debuffed</td>
    <td>Zerato (S2)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Target Buffed</td>
    <td>Yufine (S3)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Per Target Debuff</td>
    <td>Baal &amp; Sezan (S2)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Per Focus</td>
    <td>Violet (s3)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Specific Target Debuff</td>
    <td>Chloe (S1) - Nail, Gunther (S3)</td>
    <td>TBD</td>
  </tr>
  <tr>
    <td>Per Specific Target Debuff</td>
    <td>Surin (S3)</td>
    <td>TBD</td>
  </tr>
  </tbody>
</table>

**Comment by kmalone86** [comment]
Sounds good to me. You have crd list for critial damage. Everywhere else we go by chd (crit hit damage), so probably best to keep them the same.

It would probably be a good idea to store the monstrous formula with all 20 or so variables somewhere in database.

**Comment by stocky37** [comment]
> Sounds good to me. You have crd list for critial damage. Everywhere else we go by chd (crit hit damage), so probably best to keep them the same.

Nice catch.

**Comment by kmalone86** [comment]
I went through all the heroes and tried to make what the full formula would look like.

This is the example from google doc:
<pre><code>
(attack*att_rate + flat_modifier)*multiplicative_modifier*element*(1.871*pow!)/(enemyDef/300+1)*hitType
</code></pre>

I used as short as I could go per variable, but it still came out very long. This usually just meant the "name". I did not see any cases where 2 of the same "name" were needed in the same skill.
<pre><code>
(((((("atk" * (1+{"name":"statModifierSpecificBuff","stat":"atk"})
     ) +
     {"name":"hpMissingStaticAtk"}
    ) *
    ({"name":"statModifier","stat":"atk"} +
     {"name":"statModifierPerSkillBar","stat":"atk"}
    ) +
   ("hp"  * ({"name":"statModifier","stat":"hp","target":"self"} +
             {"name":"statModifier","stat":"hp","target":"target"}
            )  +
   ("def" *
     (1+{"name":"statModifierPerSpecificBuff"}) *
    {"name":"statModifier","stat":"def"})
  )
  *
  (1 + (("spd" * {"name":"statModifier","stat":"spd"})
        {"name":"specificBuff"} +
        {"name":"targetBuffed"} +
        {"name":"perSpecificBuff"} +
        {"name":"specificDebuff"} +
        {"name":"targetDebuffed"} +
        {"name":"perDebuff"} +
        {"name":"perSpecificDebuff"} +
        {"name":"hpMissing","target":"self"} +
        {"name":"hpMissing","target":"target"} +
        {"name":"perTarget"} +
        {"name":"singleTargetBonus"} +
        {"name":"perSkillBar"} +
        {"name":"hpRemaining","target":"self"}
       )
  )
  "element:[1, 1.1]" *
  (1.871*{"name":"pow"})
 )
 +
 {"name":"hpMissingStatic","target":"self"}
)
/
((enemyDef/300+1) *
 ("hit:[miss:0.75,
        normal:1.0,
        crushing:1.3,
        critical:("crd" + {"name":"statModifierStatic", "stat":"chd"})
       ]"
 )
</code></pre>

I considered passives as (hidden) buffs.

I did change a few things from what you had listed.
You had a statModifier for chd for cdom, but it wasn't really a modifier. It was a 20% damage increase, so I added "specificBuff" and treated crit as a buff.

I changed perFocus to perSkillBar to make it more generic as other heroes can use. Same with statModifierPerFocus to statModifierPerSkillBar.

Below is a list of I think ever case the variables need to get set. Anything with a "**" means it required a variable name that wasn't listed above.
<pre><code>
{"name":"pow"} --- all
{"name":"statModifier","stat":"atk"} --- all
**{"name":"statModifierSpecificBuff","stat":"atk"} --- Clarrisa(S1,S3-Passive), Gloomyrain(S1,S3-Passive)
{"name":"statModifier","stat":"hp","target":"self"} --- Zeno(S1,S3), Ras(S1,S3), Cecilia(S1,S2,S3), ML-Corvus(S1,S3),
                                                        Cartuja(S1,S3), Tywin(S1,S3), Ken(S1,S2,S3), Rin(S1,S2),
                                                        Krau(S1,S2), Taranor-RG(S1,S3), Arowell(S1,S3), Bask(S1,S2)
                                                        Choas-Axe(S3)
**{"name":"statModifier","stat":"hp","target":"target"} --- Bellona(S1), ML-Mercedes(S2), Tieria(S3), Nemunas(S2)
{"name":"statModifier","stat":"def"} --- Rose(S1), Armin(S1,S2), Corvus(S1,S2), Maya(S1,S2), ML-Maya(S1,S3),
                                         Crozet(S1,S3), Kluri(S1), Pyllis(S1,S3), Kirkirat(S1,S3), Falc-Kluri(S1),
                                         ML-Armin(S1)
{"name":"statModifier","stat":"spd"} --- Silk(S1), ML-Silk(S1,S2,S3), Vildred(S1,S3), Cidd(S1,S3), ML-Cidd(S1,S3),
                                         Coli(S1,S2,S3), ML-Coli(S1,S3), Roozid(S1,S2), Mirsa(S1,S3), Mucacha(S1,S3)
**{"name":"hpRemaining","target":"self"} --- Kise(S3),
{"name":"hpMissing","target":"self"} --- Kayron(S1,S3), ML-Ken(S2), Butcher(S3), Sven(S3,S4..)
{"name":"hpMissingStatic","target":"self"} --- Krau(S3)
{"name":"hpMissing","target":"target"} --- Mercedes(S3), ML-Vildred(S1,S3), Sez(S1,S3), Enott(S1), Axe-God(S1,S2),
                                           Lorina(S3), Choas-Axe(S1,S2), Comm-Lorina(S3)
{"name":"perTarget"} --- Bellona(S2). ML-Kise(S2)
{"name":"singleTargetBonus"} --- Mercedes(S2), Yuna(S1,S3), Haste(S3)
{"name":"targetDebuffed"} --- Zerato(S2)
{"name":"targetBuffed"} --- Yufine(S3), Romann(S3)
**{"name":"perSpecificBuff"} --- Clarissa(S1,S3-Passive), ML-Dominiel(S1-passive)
{"name":"perDebuff"} --- B&S(S2), ML-Tenebria(S3), Alexa(S3), Jena(S1)
{"name":"perSkillBar"} --- Violet(S3), Ravi(S1,S3-Passive)
**{"name":"specificBuff"} --- Silk(S1? Passive active), Clarissa(S3), ML-Dominiel(S1)
{"name":"specificDebuff"} --- Chloe(S1,S3), Gunther(S3), Wanda(S1), Pearlhorizon(S3)
{"name":"perSpecificDebuff"} --- Surin(S3)
{"name":"statModifierPerSkillBar","stat":"atk"} --- Charlotte(S3)
**{"name":"perPassive"} --- Zeno(S2)
**{"name":"statModifierStatic", "stat":"chd"} --- Karin(S3)
**{"name":"hpMissingStaticAtk"} -- ML-Karin(S1,S3-Passive)
**{"name":"statModifierPerSpecificBuff"} -- Pyllis(S1,S3-Passive)
</code></pre>

Also, I think you are right about Bellona S1, so I included it as so.

**Comment by stocky37** [comment]
Wow, nice one!  One or two minor nitpicks:

> You had a statModifier for chd for cdom, but it wasn't really a modifier. It was a 20% damage increase, so I added "specificBuff" and treated crit as a buff.

I don't think it's possible to treat crit as a specificBuff since it would also have to take into account regular critical hit damage, whereas all the other specificBuffs are just plain multipliers.

Actually that's it I tihnk XD

I probably won't look at the formula too hard tbh since I most likely won't be using it.

**Comment by kmalone86** [comment]
For Cdom, "if crit" adds a plain 20% multiplier to damage (doc doesn't say it is to crit damage), so that is before crit damage is calculated. I figured it was no different than "specificDebuff" need data on target to tell the output, crit would be the same. I have no idea how you can use the data if not looking for final result lol

**Comment by stocky37** [comment]
What I mean is that **crit damage is already just a regular damage multiplier**. if you crit, a simplified formula is just `(atk * crit damage) * crit modifier` which is exactly the same as `atk * (crit damage * crit modifier)`. In that regard, I don't particularly care where it is handled because the end result would be the same. Where the difference comes in then, is that nowhere in the formula are you handling a regular crit and taking crit damage into account.

Oh and I will be calculating actual damage numbers, I just don't particularly want to parse a giant string/object like that in order to do so. It will be so much easier to just hard code that formula into a function myself. Or better yet, into an API call that can take all the parameters and give you a result :)

**Comment by kmalone86** [comment]
That does makes sense. I guess I was just trying to follow the google doc formula too closely. They through it at the end and they didn't use many (), so made it a bit confusing.

**Comment by kmalone86** [comment]
I started a PR with the basic information that all heroes have. We will have to go back and each the special cases for each hero.
#129

**Comment by RaphaelDDL** [comment]
Let me know how I should use this data to present to the user, I still don't quite understand the `pow` and what not, I'm only used to Summoner's War being percent of some attribute(s), or some simple math when it's based off speed/hp... like "140% of ATK" or "((SPD+70)/0.3)% of ATK"

**Comment by stocky37** [comment]
Will do when I can think of it. One other thing we’re missing atm is defence penetration.

**Comment by kmalone86** [comment]
I merged the current pow & atk mod PR in, but I think I am going to add a few more fields before moving on to other values.
<pre><code>
            "damageModifiers": [
                {
                    "name": "pow",
                    "value": 0.95
                },
                {
                    "name": "statModifier",
                    "stat": "atk",
                    "type": "additive",
                    "target": "self",
                    "value": 1.0
                }
            ]
</code></pre>

I am thinking to change it to something like below, so more information is provided about the value aside from just knowing what the name means.

<pre><code>
            "damageModifiers": [
                {
                    "name": "pow",
                    "section": "pow",
                    "value": 0.95
                    "soulburn": 0.95
                },
                {
                    "name": "statModifier",
                    "section": "additive",
                    "stat": "atk",
                    "type": "multiplier",
                    "target": "self",
                    "value": 1.0
                    "soulburn": 1.0
                }
            ]
</code></pre>

I think "type" should be expanded to have other values and changed to "section". "type" was a bit weird as "additive" was used for att_rate, which is really (att_rate x ATK).
"additive|multiplicative|element|pow|enemyDefense|hit".
These values correlate to different parts of the formula, I don't know of any that would affect element and enemyDefense yet but no harm and defining values now. 

I am assuming for "multiplicative", it is  "(1 + % + %.....)" and not "(1+%) x (1+%)" as these are very different values with different results.
Example: (1 + 0.2 + 0.2) x 1.5(crit) = 2.1  vs. (1+0.2)x(1+0.2)x1.5(crit) = 2.16
The only hero I see with 2 "multiplicative" is Sven's skill 3.

Aside from that.
I added "type" to help define how "statModifier" is used.
"type": "multiplier|baseMultiplier|additive|baseAdditive"
(additive + (multiplier x (baseAdditive + (baseMultiplier x ATK)))
98% of the cases will just be multiplier x ATK, but there are a few that don't.

Lastly added, "soulburn" as most soul burns increase att_rate and sometimes even pow.

You can still grab values by name and statically add them in order if you want, but could also walk though list of values per section and calculate each section.

**Comment by RaphaelDDL** [comment]
for record, closed in favor of https://github.com/EpicSevenDB/gamedatabase/issues/250
