### ISSUE TITLE
Buffs/Debuffs

### ISSUE THREAD

**Issue by T-kON99** [EpicSevenDB/gamedatabase#124]
Add another field in each hero skills json. This will allow us to filter basically anything and use a single filter command (eg heroes.filter('buffs') or hero.filter('rarity') roughly something like this to display the result)

**Comment by stocky37** [comment]
Am I mistaken or is there not already a buff field in hero skills?

**Comment by T-kON99** [comment]
Ah yes, it appears I missed that. My bad. I looked the code from github not from my IDE hence I missed it.
