### ISSUE TITLE
Non-status buffs and debuffs enhancement

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#134]
Currently our buff/debuff only list the status icons, following game's design.

It was suggested that we could add other kind of effects which aren't status icons. I was thinking in creating the following buff/debuff codes (Below the ones I remember):

- `Combat Readiness Increase` => `efct_cr_up`
- `Combat Readiness Decrease` => `efct_cr_dn`
- `Penetrate Defense` => `efct_def_pen`
- `Cleanse` => `efct_cleanse`
- `Dispel` => `efct_dispel`
- `Cooldown Increase` => `efct_cd_up`
- `Cooldown Reduction` => `efct_cd_dn`

Any other I'm missing? 

So for example, Aramintha would have added to her S1: `efct_cd_dn` and to her S3 `efct_cr_up`.

There was also a suggestion to actually have separated versions of the buffs debuffs, per single target/AoE. Not sure how I feel about it, or how we would implement that lol.

**Comment by kmalone86** [comment]
There are a lot of hero specific buffs that were skipped as well.
Like Lidica's "Skill Nullifer" (this one probably isn't going to be unique to Lidica forever)
Ken's Vigor
Tamarinne's Idol
Loveliness
(Rin's random buff?)

As for effects,
Dual Attack => efct_dual_atk (Tamarinne, ML Clarissa)
Extra Turn=> efct_ex_turn (Celestine, Axe God, cdom)
Transfer => efct_trans  (Gloomyrain, Basar)

**Comment by RaphaelDDL** [comment]
The hero specific ones were because we didn't have the icons xD

Now we got 'em (idk about nullifier though, need to check), so I'll add the keys to their jsons, but not sure if we should add loviness/idol/vigor to the buff search since they still unique.. What you think?

Also, thanks for the other effects :)

**Comment by kmalone86** [comment]
I would say only add to search if at least 2 heroes have the buff.

**Comment by RaphaelDDL** [comment]
I'll do something different, I'll add anyway so I don't have to keep track of who has, who hasn't, which debuffs appears twice or more, etc.

**Comment by kmalone86** [comment]
@RaphaelDDL I just made a PR in databuilder that adds a these. Hopefully clean up this issue soon.



           effects: [
                {
                    title: "Increase Combat Readiness",
                    slug: "efct_cr_up",
                    checked: false
                },
                 {
                     title: "Decrease Combat Readiness",
                     slug: "efct_cr_dn",
                     checked: false
                 },
                { title: "Cleanse", slug: "efct_cleanse", checked: false },
                { title: "Decrease Cooldown", slug: "efct_cd_dn", checked: false },
                { title: "Extra Turn", slug: "efct_ex_turn", checked: false },
                { title: "Dual Attack", slug: "efct_dual_att", checked: false },
                { title: "Steal Buff", slug: "efct_steal", checked: false },
                { title: "Extinction", slug: "efct_extinct", checked: false },
                { title: "Detonate", slug: "efct_detonate", checked: false },
                 { title: "Penetrate Defense", slug: "efct_def_pen", checked: false },
                 { title: "Dispel", slug: "efct_dispel", checked: false },
                 { title: "Increase Cooldown", slug: "efct_cd_up", checked: false },
                 { title: "Transfer", slug: "efct_trans", checked: false },
                 { title: "Extinction", slug: "efct_extinct", checked: false },
                 { title: "Detonate", slug: "efct_detonate", checked: false }
            ],
           ],


A few more buffs and debuffs as well
                { title: "Random Buff", slug: "stic_rnd_buf", checked: false },
                { title: "Skill Nullifier", slug: "stic_sk_null", checked: false },
                { title: "Idol", slug: "stic_idol", checked: false },
                { title: "Vigor", slug: "stic_vigor", checked: false },
                { title: "Loveliness", slug: "stic_love", checked: false },
                { title: "Enraged", slug: "stic_enrage", checked: false }, (Corvus)
                { title: "Rage", slug: "stic_rage", checked: false } (Clarissa)

                { title: "Random Debuff", slug: "stic_rnd_debuf", checked: false }, (Basar)
                { title: "Bomb", slug: "stic_bomb", checked: false } (ml leo)

**Comment by Kenford20** [comment]
hello, I raised a PR to add json files for the buffs/debuffs directory. idk if the databuilder mentioned above automates that or something, but I went ahead and did it manually. 

feel free to bring up any suggestions/concerns!
