### ISSUE TITLE
Planning to support multi-language

### ISSUE THREAD

**Issue by jhleee** [EpicSevenDB/gamedatabase#138]
Is there any plan for support multi-language ? Korean, Chinese or Japanese etc.

**Comment by kmalone86** [comment]
There was talk a few weeks ago about adding Spanish, as a few of the guys working on this wanted it. Nothing has been done yet, but I assume a framework will be made to allow for Spanish and at that point there is no reason not to allow other languages, given we can get someone with the data to add it.

**Comment by RaphaelDDL** [comment]
for the UI part of the website itself I was already pondering between `vue-i18n` and `vue-multilanguage`. For the database, no idea yet, specially that we would need native people to translate

**Comment by kmalone86** [comment]
For database, we could changes some things in list of values.
Like
    "background": "The Holy Order of the Blue Cross requested that Reingar find a way to calm Clarissa down. Instead, the researchers focused on how cats can still be loved after wreaking havoc. Then they turned her into a cat to eliminate everyone's complaints about her violence.",

    "background": {
        "english": "The Holy Order of the Blue Cross requested that Reingar find a way to calm Clarissa down. Instead, the researchers focused on how cats can still be loved after wreaking havoc. Then they turned her into a cat to eliminate everyone's complaints about her violence.",
        "spanish": "",
        (etc)
   }

This would probably have to be done for a few things. (Basically every string that doesn't point to a file)
background, skill name, skill description, skill enhancement description, specialtySkill section(aside from stats)

**Comment by jhleee** [comment]
What about file-based classification? (like, `hero/en/armin.json`, `hero/ko/armin.json`) It can keep format and  reduce unnecessary resource loading.

**Comment by stocky37** [comment]
There would be a lot of duplication in that I guess.

**Comment by kmalone86** [comment]
Yeah I was trying to avoid duplication. I would rather not have to change 10 language files every time they change a number value.
80% of each file is either a number like stat atk: 1000 or a well defined name like soul-weaver. This defined name would generally point to a file, which would probably vary based on selected language.

**Comment by RaphaelDDL** [comment]
I think the way Kromag suggested should be the way. Every translate-able property become an object with `en` and the other locale strings as prop.


    "background": {
        "en": "thanks",
        "jp": "arigato",
        "cn": "xiexie",
    }

Then I could make an util on ui to grab the current locale or default to `en`

**Comment by jhleee** [comment]
I got it, thanks everyone for consider about it.

**Comment by jhleee** [comment]
@RaphaelDDL Can you create a new branch for `i18n` ? I already translated `en` to `ko` for prototype.

**Comment by kmalone86** [comment]
@jhleee Raphael is busy the next 2 weeks, so he may not respond.

**Comment by Dimbreath** [comment]
Since this has been brought up a lot of times recently and both the website and my bot are getting translations I think it might be a good idea to see how we do this.

I do find we'll still have a lot of duplication, especially when it comes to stuff like enhancement skill descriptions or basically anything we don't know how constant it might be throughout all the files _(which is not the case of for example camping reactions, items on skill enhancement, etc)_

**Comment by RaphaelDDL** [comment]
Just updating this:
https://api.epicsevendb.com/api/v2/artifact/bloodstone?lang=jp

Langs are `kr,cn,jp,de,pt,es,en,fr`

V2 API is multi-lang. Artifact is already released, now working on Heroes.

**Comment by zx900930** [comment]
You should add Chinese Traditional `tw` to the Langs list,too.
I can help with the Chinese Simplified `cn` translation.
And the heros name are already translated here:
[https://github.com/zx900930/maphe.github.io/blob/master/e7-damage-calc/lang.js](url)

**Comment by Dimbreath** [comment]
We're grabbing them directly from the database files. Is the game currently translated to Traditional Chinese? Otherwise everything would need to be translated.

For reference: https://github.com/EpicSevenDB/gamedatabase/tree/v2api/src/text

**Comment by zx900930** [comment]
> We're grabbing them directly from the database files. Is the game currently translated to Traditional Chinese? Otherwise everything would need to be translated.
> 
> For reference: https://github.com/EpicSevenDB/gamedatabase/tree/v2api/src/text

The game currently translated to Traditional Chinese, and from Traditional Chinese to Simplified Chinese, you could use [this project](https://github.com/BYVoid/OpenCC) to auto translate it.

**Comment by RaphaelDDL** [comment]
So, the question is, what exactly is different between chineses? Like, I was planning on just supporting the game languages because in the end, that's what the game support and what the options are to play, so whoever is playing is tied to them anyway

**Comment by zx900930** [comment]
@RaphaelDDL The core problem is the searching function is not working(Search a string in Simplified Chinese return 0 results). 
Perhaps this game will support Simplified Chinese in the future like Summoners War.
No need to add it now.

**Comment by RaphaelDDL** [comment]
Oh, it's because I didn't flip the switch from v1 to v2 on the website yet :(

I have the branch with the changes, but still missing the fix on the list filters, since I'll need to rewrite them. Only artifacts use v2

**Comment by Dimbreath** [comment]
Well I think we can always support fan-made translations in other languages but the issue would be that people need to keep these updated and it's not easy task since as we're talking now there's over 3000 text strings? (And that's missing a handful few still from Item Drops because it has node names, Specialty Change trees, etc)

**Comment by zx900930** [comment]
@Dimbreath in fact 'zht' to 'zhs' is a "transcode" other than translate, and there are tools already do the job. no matter how much the strings are, they can be translated in few secs.
like
`{"results":[{"_id":"bloodstone","identifier":"efr01","name":"血玉髓","rarity":5,"role":"ranger","limited":false,"description":"才咬下一口水果，鮮紅的液體便伴隨著嚇人的聲響溢出。撲鼻而來的不是血腥味，而是微甜的水果香。","assets":{"icon":"icon_art4_17","image":"art4_17_fu","thumbnail":"art4_17_l"},"stats":{"attack":21,"health":32},"skill":{"description":"攻擊後使生命力比例最低的我軍恢復相當於傷害量{{variable}}的生命力。","enhancements":[[0.13],[0.143],[0.156],[0.169],[0.182],[0.195],[0.208],[0.221],[0.234],[0.247],[0.26]]}}],"meta":{"requestDate":"Tue Mar 31 13:56:10 UTC 2020","apiVersion":"1.0.0","IMPORTANT":"V2 is out @ https://api.epicsevendb.com/ and V1 is now deprecated and will not receive updates. Please see more details in the announcement @ https://epicsevendb-apiserver.herokuapp.com/ documentation homepage."}}`

to

`{"results":[{"_id":"bloodstone","identifier":"efr01","name":"血玉髓","rarity":5,"role":"ranger","limited":false,"description":"才咬下一口水果，鲜红的液体便伴随著吓人的声响溢出。扑鼻而来的不是血腥味，而是微甜的水果香。","assets":{"icon":"icon_art4_17","image":"art4_17_fu","thumbnail":"art4_17_l"},"stats":{"attack":21,"health":32},"skill":{"description":"攻击后使生命力比例最低的我军恢复相当于伤害量{{variable}}的生命力。","enhancements":[[0.13],[0.143],[0.156],[0.169],[0.182],[0.195],[0.208],[0.221],[0.234],[0.247],[0.26]]}}],"meta":{"requestDate":"Tue Mar 31 13:56:10 UTC 2020","apiVersion":"1.0.0","IMPORTANT":"V2 is out @ https://api.epicsevendb.com/ and V1 is now deprecated and will not receive updates. Please see more details in the announcement @ https://epicsevendb-apiserver.herokuapp.com/ documentation homepage."}}`

**Comment by Dimbreath** [comment]
@zx900930 Just an update, there's only one missing feature before this can be done. I'm not sure what @RaphaelDDL thinks yet, he's been busy recently but other than that I think we're nearly done.

**Comment by zx900930** [comment]
@Dimbreath ok，I 'll waiting for you guys to finish the work.

**Comment by RaphaelDDL** [comment]
Going back on this, I think it should be fine now to start this.

@zx900930 Can you tell me if these answers are correct? 

- https://stackoverflow.com/a/4894443/684932
- https://stackoverflow.com/a/4894634/684932 

So, if I understand correctly, China and Singapore uses Chinese Simplified (zhs) whereas others countries (Taiwan, Hong Kong, etc) use Chinese Traditional (zht). And game has zht. 

So, thinking on isocodes and the country codes I must fix. Right now I'm using `zh-CN` as the isocode and `/cn/` in url.  But if that info I found is accurate, I'm using it wrongly as zh-CN would've been for zhs, not zht.

Okay, so first I need to change the current zht implementation from `zh-CN`|`/cn/` into `zh-TW`/`/tw/`, and then create a new file zhs and that one I'll point to `zh-CN`|`/cn/`.

And on the static texts, I'll have to use the same tool to convert the static texts too @ https://github.com/EpicSevenDB/ui/blob/master/lang/zh-CN.js (and also rename that to zh-TW).

Correct?

**Comment by zx900930** [comment]
@RaphaelDDL no reason to change zhs zht to zh-CN and zh-TW
In i18n standard the simplified chinese is zh-Hans (short version zhs)  which includes (zh-CN, zh-SG)
And traditional chinese is zh-Hant (short version zht) which includes (zh-TW, zh-HK etc)

If you need to differentiate between Chinese languages(which is not the case in a game like Epic Seven or any other games or softwares), you could use language codes like zh-CN zh-TW . otherwise zht and zhs is sufficient(zht and zhs is widely used in software localization)

And if Epic Seven release the Simplified Chinese language, the code is probably zhs not zh-CN.

**Comment by RaphaelDDL** [comment]
Awesome, thank you. 
I'll do the changes this weekend.

**Comment by Dimbreath** [comment]
@zx900930 I do want to note they added their own translations as of the current game version.

**Comment by zx900930** [comment]
@zx900930 What? they are added simplified chinese into the game?  Maybe they finally got the license to run epic seven in China mainland.

**Comment by zx900930** [comment]
@Dimbreath I quickly findout they are not simply copy paste translations,  like the newest
c1101 choux's translation are totally different.

**Comment by Dimbreath** [comment]
Interesting. What are the translation for both? I think this is nothing new in the game though. _(Heard it happened with Korean <-> English translations.)_

**Comment by zx900930** [comment]
@Dimbreath  the zht transltion is the meaning of choux(the food),  and the zhs translation is the choux's prononciation.
