### ISSUE TITLE
Mispelling on diene.awakening.statsIncrease[0] on rank 1 and rank 5

### ISSUE THREAD

**Issue by QuazzyWazzy** [EpicSevenDB/gamedatabase#144]
Should be "efr" instead of "afr" for Effect Resistance
Discovered by Azioria#1394

![image](https://user-images.githubusercontent.com/42061128/54169571-29ee6b80-44ae-11e9-9c79-7bb3cbf60cb3.png)

**Comment by kmalone86** [comment]
Fixed, thanks.
