### ISSUE TITLE
Skill Level Up materials

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#15]
Raising up for discussion:

I actually didn't think of the Skill Level Up materials to be fair. I'm noob so I don't even leveled up skills past level one so I thought all heroes would cost same amount for all skills on all levels.. like, lv1 be one molagora, lv2 3 of them, and so on.

So @Triharder-E7 pointed on #14 as well as what reddit user Pirafies told me at https://old.reddit.com/r/EpicSeven/comments/a19v99/epicsevendbcom_help_request_to_the_community_for/eaookhh/

And it makes super sense. His suggestion kinda copy the scheme of awakening resources, so could be something like, from:

            "enhancement": [
                "+5% damage dealt",
                "+5% damage dealt",
                "+5% damage dealt",
                "+5% damage dealt",
                "+10% damage dealt"
            ],

to:

	"enhancement": [{
	  "description": "+5% damage dealt",
	  "resources": [{
		"item": "molagora",
		"qty": 1
	  }]
	}, {
	  "description": "+5% damage dealt",
	  "resources": [{
		"item": "molagora",
		"qty": 3
	  }]
	}]

Are we okay with making this update?

**Comment by kmalone86** [comment]
Sounds good to me.  I am not sure if there is a formulaic way to figure out every resource needed like formation bonus, so we will probably have a lot of blank spots for a while.

**Comment by Triharder-E7** [comment]
I'm obviously all for it, but format wise I personally like how it's written with Star Awakenings:

```
"enhancement": [{
  "description": "+5% damage dealt",
  "resources": [{ "item": "molagora", "qty": 1 }, { "item": "gold", "qty": 4000 }]
}, {
  "description": "+5% damage dealt",
  "resources": [{ "item": "molagora", "qty": 2 }, { "item": "gold", "qty": 8000 }]
}]
```

Also, do you want us to include gold cost as well? I *think* they are static depending on the level of enhancement that skill is on. E.g. the first enhancement for Skill 1 will cost 4,000g, the second will cost 8,000g, third 12,000g and on and on. It might vary depending on hero's base rarity though. Game is down for maintenance, so these numbers are just placeholders, as I can't really check.

Lastly, @kmalone86 you can go to hero > skill enhance in game, navigate to the hero (If you own it), and once you've selected a skill, you can press down on the various enhancement levels on the left and it will show you the materials required for that specific rank. This doesn't seem to work in the journal, so you need to have the hero to check as far as I'm aware.

**Comment by kmalone86** [comment]
@Triharder-E7  That is good then. That is the problem when the game is down, can't check. Some of the rarer units may be problematic, but that is minor.

**Comment by RaphaelDDL** [comment]
@Triharder-E7  I guess we can add the gold too, since it's listed as a separated item (on resources folder) and also because it's an actual cost anyway.

Tomorrow I'll update Ras with this, at least for the placeholder, I don't have the data.

Cool, we are settled with same approach as awakening ones.

**Comment by RaphaelDDL** [comment]
I'll update Ras with this object then, since he's the example unit.

**Comment by RaphaelDDL** [comment]
Also created a `_HERO_TEMPLATE.json` on `hero` folder for all new submissions.

Let me know if Ras or the hero template has anything missing or wrong. Thanks.
