### ISSUE TITLE
Celestial Mercedes - wrong skill 3 combat readiness

### ISSUE THREAD

**Issue by akrassikov** [EpicSevenDB/gamedatabase#151]
In the database, Celestial Mercedes S3 "Finale" has 15% increased combat readiness per critical hit instead of 20% which is reported in the update notes and in the game.

Source:
http://page.onstove.com/epicseven/global/board/list/e7en001/view/2871954

![Screenshot_2019-03-30-15-28-39](https://user-images.githubusercontent.com/1063623/55281967-ab992280-5311-11e9-8145-ef895e13e471.png)

**Comment by kmalone86** [comment]
Zealtron fixed the issue in DB, thanks.
