### ISSUE TITLE
Nilgal json, data consistency issue

### ISSUE THREAD

**Issue by tedahn** [EpicSevenDB/gamedatabase#153]
I just ran into just a small issue.
```
    "specialtySkill": {
        "name": "",
        "description": "",
        "dispatch": [],
        "enhancement": [],
        "stats": {
            "command": 0,
            "charm": 0,
            "politics": 0
        }
    },
```
The following data under the hero "Nilgal.json" has a small inconsistency.
Dispatch and Enhancement variables should be String (like other hero json files) and not Array.

**Comment by RaphaelDDL** [comment]
Fixed, thanks :)
