### ISSUE TITLE
Issues on few heroes (sent by Kongou)

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#154]
He's currently using the api for his android app ( https://play.google.com/store/apps/details?id=com.tedahn.epicseveninfo ) so he pointed out a few inconsistencies:

## Here is the list for the type errors:

1. Assassin Cartuja
    - "selfSkillBarValue":"" --> should be integer 0, instead of empty string.
2. Kikirat v2
    - "dispatch":[] --> should be empty string "", instead of empty array.
    - "enhancement":[] --> should be empty string "", instead of empty array.
3. Kitty Clarissa
    - "occult":"Unknown" --> should be integer 0, instead of string. 
4. Nigal
    - "dispatch":[] --> should be empty string "", instead of empty array.
    - "enhancement":[] --> should be empty string "", instead of empty array.
5. Tenebria
    - "skills": [{ ... "buffs":"" ... }]  --> "buffs" should be empty array instead of empty string 

Kitty Clarissa seems there's some data missing. 

## Buff/Debuff typo list:

1. Tywin S2(Commanding Shout) - atk_up --> att_up
2. Cidd S1 - spd_up --> speed_up
3. Jecht S3 - spd_up --> speed_up
4. Watcher Schuri S2 - spd_up --> speed_up
5. Righteous Thief Roozid S1 - dspeed_dn --> speed_dn

**Comment by kmalone86** [comment]
Cool, at least they are all minor.

**Comment by RaphaelDDL** [comment]
#154 fixed this, thank you @kmalone86
