### ISSUE TITLE
AP Shop data for Catalysts?

### ISSUE THREAD

**Issue by tedahn** [EpicSevenDB/gamedatabase#156]
I think it'll be useful to have AP shops data. It's a good end game way of making non-event catalyst farming efficient. World and Normal share the same data

So we can have the data something like this?

```
{
  "apshops":
  {
    "1":{
      "items":[
        {
          "name":"fighter-medal",
          "qty": 2, 
          "cost":400
        },
        {
          "name":"slime-jelly",
          "qty": 5, 
          "cost":120
        }, 
        {
          "name":"blessing-of-orbis",
          "qty": 5, 
          "cost":120
          
        },
        {
          "name":"eternal-forest-dust",
          "qty": 5, 
          "cost":120
        }
        ]
    },
    "2":{...},
    "2S":{...},
    "3":{...},
    "3S":{...},
    "4-1":{...},
    "4-2":{...},
    ...
  }
}
```

OR 

Just add an array to every Catalyst like 

```
{
  "fileId":"eternal-forest-dust"
  ...
  "apshops": ["1","4-2","7"]
}
```

I suggest the first method and have the api be able to generate list of shops catalysts are available in. 

It will make the data a lot more editable in the future AP shops change.

**Comment by Dimbreath** [comment]
This was added on #9b4dcde.
