### ISSUE TITLE
Mage speed update with 9/4 update

### ISSUE THREAD

**Issue by bubbabri** [EpicSevenDB/gamedatabase#206]
Not sure if i should do a fork or if someone was already on it, but noticed the mages that got speed increases have not been updated yet.
![mage speed](https://user-images.githubusercontent.com/47728669/64468710-daec6080-d0f5-11e9-881e-5a999f130efd.png)

**Comment by kmalone86** [comment]
Thanks for noticing,  forgot to add that.  I can add it in a little later.

**Comment by RaphaelDDL** [comment]
#207 merged, will update site n api shortly.

Thank you for reminding @bubbabri
