### ISSUE TITLE
Database api missing information

### ISSUE THREAD

**Issue by Sevih** [EpicSevenDB/gamedatabase#212]
Hello,
Vivian memoryImprintAttribute is empty.
https://epicsevendb-apiserver.herokuapp.com/api/hero/vivian

https://i.imgur.com/CyvAywl.png

**Comment by kmalone86** [comment]
Nice catch, fixed. Just need @RaphaelDDL to merge to apiserver.

**Comment by Sevih** [comment]
Thanks for this speedy reaction

**Comment by RaphaelDDL** [comment]
mongo updated, API fixed. Thank you both

https://api.epicsevendb.com/api/hero/vivian
