### ISSUE TITLE
Possible enemy hp damage modifier bug?

### ISSUE THREAD

**Issue by AlexeiA** [EpicSevenDB/gamedatabase#224]
Skills with damage scaling by enemy's HP, e.g. Bellona's or Sol's, have damageMultiplier `hp_rate`, and their formula contains `hero_hp` argument. 
I.e. `((atk_rate * hero_atk) + (hp_rate * hero_hp)) * pow! * constant`
Shouldn't it be something like `enemy_hp_rate` and `enemy_hp`?

**Comment by kmalone86** [comment]
Nice catch, fixed.
