### ISSUE TITLE
Database missing data

### ISSUE THREAD

**Issue by Sevih** [EpicSevenDB/gamedatabase#235]
Hello,
following skills got no image  :

arbiter-vildred/sk_2p.png
charles/sk_2.png
maid-chloe/sk_2p.png
crimson-armin/sk_2p.png
adlay/sk_1.png
adlay/sk_2p.png
adlay/sk_3.png
alexa/sk_1.png
alexa/sk_2.png
alexa/sk_3.png
arowell/sk_1.png
arowell/sk_2p
arowell/sk_3
azalea/sk_1.png
azalea/sk_2.png
azalea/sk_3.png
carmainerose/sk_1.png
carmainerose/sk_2.png
carmainerose/sk_3.png
carrot/sk_1.png
carrot/sk_2p.png
carrot/sk_3.png
celeste/sk_1.png
celeste/sk_2.png
celeste/sk_3.png
church-of-ilryos-axe/sk_1.png
church-of-ilryos-axe/sk_2.png
church-of-ilryos-axe/sk_3.png

Following character got no Ex equip :
Charles : https://epicsevendb-apiserver.herokuapp.com/api/hero/charles
Blaze Dingo : https://epicsevendb-apiserver.herokuapp.com/api/hero/blaze-dingo
Tywin : https://epicsevendb-apiserver.herokuapp.com/api/hero/tywin
Yuna : https://epicsevendb-apiserver.herokuapp.com/api/hero/yuna

**Comment by RaphaelDDL** [comment]
With the V2 soon coming, it'll come with the assets to be used (that is, I won't need to rename manually each hero, instead we'll use game naming). Example:

https://api.epicsevendb.com/api/v2/hero/aramintha

Skills have `icon` naming now, with the `id` we'll be able to pull all hero's images.

**Comment by Dimbreath** [comment]
Assets are too uploaded an character got their exclusive equipment on the API too. Note that v2 API for heroes is not public yet, but the data is there.
