### ISSUE TITLE
Please check eff res

### ISSUE THREAD

**Issue by motionsky** [EpicSevenDB/gamedatabase#239]
![Screenshot_2019-12-01-14-55-19-23](https://user-images.githubusercontent.com/40865908/69910759-7ff3ac80-144b-11ea-8aec-b4e478def1a3.png)

**Comment by RaphaelDDL** [comment]
Thanks for the report.
On the website https://epicsevendb.com/hero/kikirat-v2 the values are correct. I've pinged @Dimbreath to fix on Yufine bot :)

**Comment by Dimbreath** [comment]
Will be updating in a few minutes. Thanks for noticing!

**Comment by Dimbreath** [comment]
Well, I forgot to update the issue. It's an issue on the actual JSON, I'm not sure why it isn't reflected on the website itself but https://github.com/EpicSevenDB/gamedatabase/blob/master/src/hero/kikirat-v2.json#L52

**Comment by RaphaelDDL** [comment]
Fixed on the json. You should be able to update Yufine with latest :D
I'll update website db too.

**Comment by Dimbreath** [comment]
This is fixed.
