### ISSUE TITLE
Faithless Lidica

### ISSUE THREAD

**Issue by soonertoucan** [EpicSevenDB/gamedatabase#241]
It appears Faithless Lidica is still in preview mode. This is causing some issues with applications that use the API to pull the unit data.

**Comment by RaphaelDDL** [comment]
Data updated thanks to @kmalone86 
I'll update the DB tonight. I just don't have the unit's assets yet.


Out of curiosity, which tool you are using :)?

**Comment by RaphaelDDL** [comment]
DB updated. Added the basic images, missing skill ones.
