### ISSUE TITLE
Alencia and Benevolent Romann data missing

### ISSUE THREAD

**Issue by daddyrubin** [EpicSevenDB/gamedatabase#243]
Can the data for these 2 heroes be added?

**Comment by RaphaelDDL** [comment]
Data added, will update the DB tonight

**Comment by RaphaelDDL** [comment]
K, sorry for delay. Updated:
https://epicsevendb.com/hero/benevolent-romann
https://epicsevendb.com/hero/alencia

Will get their images next with @Dimbreath
