### ISSUE TITLE
Missing or Delayed Data

### ISSUE THREAD

**Issue by KillerBotK** [EpicSevenDB/gamedatabase#246]
I've noticed it can sometimes take weeks for new units to appear (for instance Kawerick is still not up after almost 3 weeks).  Is there anything that the public can do to speed these things along?  Happy to help out if so.

**Comment by Dimbreath** [comment]
That's because we're transitioning to v2 API which is yet not applied onto the website. The data for all the heroes up until now are on the repository already.

**Comment by KillerBotK** [comment]
Ah ok.  Never mind.  Just wondered if I could help but sounds like you've got it handled.
