### ISSUE TITLE
Elphelt's images missing

### ISSUE THREAD

**Issue by zx900930** [EpicSevenDB/gamedatabase#249]
"assets": {
        "icon": "https://assets.epicsevendb.com/_source/face/c1105_s.png",
        "image": "https://assets.epicsevendb.com/_source/face/c1105_su.png",
        "thumbnail": "https://assets.epicsevendb.com/_source/face/c1105_l.png"
      }

all returns 404 not found.

**Comment by Dimbreath** [comment]
Yes, aware of it. Uploading soon, Raph will have to update when he wakes up.

**Comment by RaphaelDDL** [comment]
Assets upgraded. Thank you
