### ISSUE TITLE
missing stats entries (lv60SixStarFullyAwakened  )

### ISSUE THREAD

**Issue by etilworg** [EpicSevenDB/gamedatabase#251]
In the page i can see the stats for different level + awakenings

https://epicsevendb.com/hero/blood-moon-haste

Level 50 at 5★ (no awakening)
Level 50 at 5★ (All Awakenings)
Level 60 at 6★ (no awakening)
Level 60 at 6★ (All Awakenings)

But the api dont return the stats block

    "stats": {
        "bra": 52,
        "int": 79,
        "fai": 98,
        "des": 61
    },

**Comment by Dimbreath** [comment]
They should be at the bottom of the API request: https://api.epicsevendb.com/hero/yufine

```"calculatedStatus": {
  "lv50FiveStarNoAwaken": {
    "cp": 11958,
    "atk": 793,
    "hp": 4267,
    "spd": 109,
    "def": 446,
    "chc": 0.15,
    "chd": 1.5,
    "dac": 0.05,
    "eff": 0,
    "efr": 0
  },
  "lv50FiveStarFullyAwakened": {
    "cp": 13624,
    "atk": 984,
    "hp": 4607,
    "spd": 109,
    "def": 446,
    "chc": 0.22999999999999998,
    "chd": 1.55,
    "dac": 0.05,
    "eff": 0,
    "efr": 0
  },
  "lv60SixStarNoAwaken": {
    "cp": 14926,
    "atk": 989,
    "hp": 5364,
    "spd": 109,
    "def": 553,
    "chc": 0.15,
    "chd": 1.5,
    "dac": 0.05,
    "eff": 0,
    "efr": 0
  },
  "lv60SixStarFullyAwakened": {
    "cp": 17106,
    "atk": 1228,
    "hp": 5784,
    "spd": 109,
    "def": 553,
    "chc": 0.22999999999999998,
    "chd": 1.65,
    "dac": 0.05,
    "eff": 0,
    "efr": 0
  }
}```

**Comment by etilworg** [comment]
tnx. 

"calculatedStatus":
 {
    "lv50FiveStarNoAwaken":{ ... },
    "lv50FiveStarFullyAwakened":{...}, 
    "lv60SixStarNoAwaken":{...}, 
    "lv60SixStarFullyAwakened": {..}
    }
