### ISSUE TITLE
Specialty Change data (runetree) in base hero instead of the SChange'd one

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#254]
Pulled from https://github.com/EpicSevenDB/api/issues/13 since is a data issue rather than the API that serves it.

The Specialty Change information (properties `changed_skill`, `quests`, `tree` in `specialty_change`) are being stored in the base hero e.g. Lorina ( https://github.com/EpicSevenDB/gamedatabase/blob/master/src/hero/lorina.json#L601 ) , instead of the SChanged one ( https://github.com/EpicSevenDB/gamedatabase/blob/master/src/hero/commander-lorina.json#L603 ).

The `id` in `specialty_change` should be kept in the base so we can have the information that the base hero has a SC available and which 'new' hero is.

`tree` for sure needs to be moved into the SC form. Not entirely sure about the `quests` and `changed_skill`, but because the SC form would already have the quests "done", I believe it would be better fit to have the quests for SC to be in the stock, presentation wise. Same for changed skill.

@Dimbreath Does the game store all SC info in the stock or/and is something we can do to move the runetree to the SChange'd one?

**Comment by Dimbreath** [comment]
Regarding this issue I did the following commits:

- [Added quick reference on base hero to the specialty change hero id. 54df58e](https://github.com/EpicSevenDB/gamedatabase/commit/3322de6a034f1a6854c7d13e903f35b09ffbf93a)
- [Moved the specialty change tree from the base hero to the specialty hero JSON. Quests remain in the base hero as it was the most logical. 3322de6](https://github.com/EpicSevenDB/gamedatabase/commit/1575d6b97878f0d5be1827aa402a69e81b71dce6)
- [Added a reference to the base hero on the specialty change hero JSON. #1575d6b](https://github.com/EpicSevenDB/gamedatabase/commit/1575d6b97878f0d5be1827aa402a69e81b71dce6)
