### ISSUE TITLE
Kikirat V2 camp data 

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#255]
Pulled from https://github.com/EpicSevenDB/ui/issues/42

I remember he didn't have camping stuff since the beginning but I just double checked in game using my Kikirat in the Labyrinth, it actually does increase/decrease Friendship/Morale based on his camp choices ("Belief" and "Unique Comment"), so they implemented a value table when gave him camp lines (correct me if I'm wrong but I think it used to not have camp lines before, right)

Can we double check this data in-game @Dimbreath ?

**Comment by Dimbreath** [comment]
He has no personalities, therefore he can't have camping values. Only has two topics as you mentioned. You need personality values to calculate camping values.

**Comment by RaphaelDDL** [comment]
Understood.

So yeah, he can affect someone else's by applying belief into their personalities, which is why he saying something does generate values. But since he has no personalities, he has no values, therefore doesn't matter what anyone says, it'll always be `-` in-game.. I just tested and even Yuna does not get a reaction from it lol. 

It's quite interesting actually, Belief saying about killing all humans makes Yuna and Tammarine happy, while Unique Comment about flat soda being good to remove stains displeases Yuna, though Charles likes hahahah.



Well, I guess there's nothing to be done here then. Adding all `values` as `0` is misleading because he has no `personalities` to match to.

**Comment by RaphaelDDL** [comment]
cc @meowyih

**Comment by Dimbreath** [comment]
I don't think they gave much thought to camping stuff lol.
