### ISSUE TITLE
Ains is missing his second skill

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#257]
From https://github.com/EpicSevenDB/api/issues/15

Ains skill 2 enhancements is empty, and API lookup fails and stops rendering the skill 2 https://github.com/EpicSevenDB/gamedatabase/blob/master/src/hero/ains.json#L409

**Comment by Dimbreath** [comment]
Will be fixed with the new batch of changes hopefully soon(tm)

**Comment by Dimbreath** [comment]
Fixed on [54df58e
](https://github.com/EpicSevenDB/gamedatabase/commit/54df58e6b4f86c527f5c6cc5ff39fb04511477e1).
