### ISSUE TITLE
assets.epicsevendb.com down?

### ISSUE THREAD

**Issue by zx900930** [EpicSevenDB/gamedatabase#258]
for example: https://assets.epicsevendb.com/_source/face/c3065_l.png return 404 not found

**Comment by Dimbreath** [comment]
Raph has to fix/change the endpoint. He's already aware.

**Comment by RaphaelDDL** [comment]
I was dumb and made the symlink to the new game data folder wrongly hahahah

I fixed it now, it's back.

Sorry D:
