### ISSUE TITLE
Project still running ?

### ISSUE THREAD

**Issue by Macharius92** [EpicSevenDB/gamedatabase#259]
Hi there,

I was using this database through your API to fill fields into a little webpage which helps my guildmates to generate GvG battle reports (heroes and artifacts)

But it looks like we didn't get any new data since Politis and the January Balance Patch. Any chance we got an update soon ? Or is the project almost dead ?

**Comment by Dimbreath** [comment]
I've been quite busy and dealing with other problems. It'll be updated tonight. Apologies.

**Comment by Macharius92** [comment]
No problem and no emergency. It was just to know if the project is still alive or not !;)

**Comment by RaphaelDDL** [comment]
I've also been sick for the past weeks so I didn't even bothered Dim with the updates lol.
