### ISSUE TITLE
Memory Imprint effect formation

### ISSUE THREAD

**Issue by RaphaelDDL** [EpicSevenDB/gamedatabase#39]
@kmalone86 mentioned on #38 that Memory Imprint effects can have positioning/formation requirements:

Like Silk's
....[..]
[..]...[X]
....[X]

lol I wasn't even aware the Imprints had positioning until he mentioned rofl.
What you guys think? Add a new property like this? Example: Silk

    "memoryImprintFormation": {
        "top":true,
        "bottom":false,
        "left":true,
        "right":false
    }

**Comment by kmalone86** [comment]
That works for me.  A lot of them are for all locations, guessing that non-5\* with a % stat bonus are probably not all locations like silk in this case.

**Comment by kevin-quach** [comment]
Oops, just saw this, I will update the tool.

**Comment by kmalone86** [comment]
This may be a bit much to add right now, but may be nice to add in camp conversation points in the future. Some tools have been going around on reddit to make teams that give the most points in lab camp, though servers kept being over subscribed.

Also the website looks great, keep up the great work.

**Comment by RaphaelDDL** [comment]
Let's plan a roadmap of things to add. I'll make a new issue with it

> Also the website looks great, keep up the great work.

Wouldn't be able without the help of all of you, so it's our achievement :)

**Comment by RaphaelDDL** [comment]
Closing since imprint obj was implemented

camp chat will be another thing, probl on the camp simulator
