### ISSUE TITLE
Stats without awakenings

### ISSUE THREAD

**Issue by stocky37** [EpicSevenDB/gamedatabase#66]
Would you be interested in a PR containing the stats for all heroes at 5* lvl 50 and 6* lvl 60 with 0 awakenings? I'll be adding them to my fork anyway since I want to use those values but thought I'd see if you would be interested while I'm at it.

Ideally we would be able to calculate their other stats at any level/star based off of their base stats but I haven't looked into it too much/figured it out yet.

**Comment by kmalone86** [comment]
More data isn't bad to have. It just adds more time to compete heroes. I have been wondering about the lvl 60 without awakening for a while, but figured I would wait till after all the heroes were done.

**Comment by stocky37** [comment]
No worries, I can just keep it in a separate branch in my fork or PR like I did with this one and keep it up to date until you decide to use it or not.
