### ISSUE TITLE
[Enhancement] Display expression for each Heroes

### ISSUE THREAD

**Issue by yonkishum** [EpicSevenDB/gamedatabase#70]
It's seems in Reddit there many people like see all expression for the Heroes, would be great make a collection of all heroes expression and display it in they own page.

**Comment by RaphaelDDL** [comment]
Oh ya, I've seen people post lots of lv10 expressions.

That's a great suggestion. When we are able to mine the faces, we'll add them. We still couldn't mine the moving artworks of the Hero screen. I think so far we have only Lots faces :(

But anyway, good suggestion, I'll add to the Roadmap.

**Comment by RaphaelDDL** [comment]
Closing here in favor of https://github.com/EpicSevenDB/ui/issues/22 since it's more of a UI enhancement than DB one.

And still do not have the expressions :/ 
But they are separated from body so would've need to manually place on top of the hero image. Not that hard with css, though.
